### ISSUE TITLE
Add util postversion hook to repush major version tag

### ISSUE THREAD

**Issue by domharrington** [readmeio/readme-micro#9]
Grab this from @kanadgupta

**Comment by cvan** [comment]
oh nice. I was some GitHub actions that automatically handles this, in semver fashion. how do we feel about actions requiring actions? at least, there is some sense of peace in knowing the package will probably continue to be maintained without additional work on ReadMe's end.

**Comment by kanadgupta** [comment]
GitHub's registry doesn't follow semver the same way `npm` does, it only uses existing git refs (i.e. branches, tags, SHAs)[^1]. So you'll need to publish and force-update a `v2` tag.

[GitHub does this themselves with `actions/checkout`](https://github.com/actions/checkout/tree/v3). We've been auto-publishing major tags like this in `rdme` and it's been [quite successful](https://github.com/readmeio/rdme/pkgs/container/rdme/versions) in getting users onto the latest version in a timely manner.

[^1]: See GitHub's docs on this: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsuses
